### PR TITLE
Friendship v1

### PR DESCRIPTION
**Pull request by somoye123**
This pull request contains the working version of the association between users and friendships tables

### CODE REVIEW

**Review by stratospherique — CHANGES_REQUESTED** [review]
### Great Start @team :clap: Associations are good :100: However, some requirements need to be implemented in order to get approval for this milestone. Check :arrow_down: 

- **[REQUIRED]** Pull request should display passing :heavy_check_mark: code linter checks.
#### Behaviour :warning: Required :warning: 
* [x] User can invite friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/send_invitation.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
* [x] User can see friendships requests ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/pending_request.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
* [x] User has to accept friendship request to start friendship ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
* [x] User can reject a friendship request ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
* [x] There is a button to invite user to friendship on users list page and on single user page ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
* [x] Posts timeline includes posts written by logged-in user and their friends ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
* [x] Unit and integration tests are added ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/tests.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
### That's it :relieved: When finished, kindly submit a code re-review request :pray: 

Happy coding :v: 
**_Ahmed Mahfoudh_**

**Comment by acushlakoncept** [comment]
All recommended changes have been implemented and the RSpec test is done.
ror-social

**Review by mosesogwo — CHANGES_REQUESTED** [review]
**Hello! :wave: Good progress here.:+1: But we still have some changes to make:**

:point_right: You now have buttons to invite friends on the "All users" page, but it is not present on a single user's page. Please add this.

:point_right: You have added unit tests but integration tests are missing. Please add integration tests for all your features in this milestone- inviting, accepting and rejecting a friend. Ideally, you should have integration tests for every other feature - authentication and posts.

:point_right: Your unit tests are not complete. Please test all validations. For example you didn't test validation of length for name of user. You can look into using shoulda_matchers for this. It is very easy to use. Also, write unit tests for all the model methods in User model that are relevant to this milestone.


_**Kindly make these changes and submit another code review request.**_

**Any questions? You can reach me on Slack (Moses Ogwo)**

**Cheers:stars:**

### Status: Changes Requested:exclamation:

**Review by davidmrtz-dev — CHANGES_REQUESTED** [review]
## Hi Team  👨‍🚀 
### Very good job so far implementing the required changes listed by the previous TSE's.

However, there are some issues that need to be addressed.  👨‍💻  ⬇️ 
Please check out below.

****

- [ ] Users index and show views .

There's an issue after sending a friend request, as you can see after sending the request I got displayed the "button" (it is clickable) "Pending" which is correct but also it still displaying the invite "button" that should be removed after sending the request.
The same issue appears on the show page of a user who has already been dispatched a friend request.
Please, fix this issue in order to display the correct info to the current user.

Screen Shot 2020-08-15 at 1 47 30 PM

****

- [ ] Friendships.
As the user, after sending a friend request and then access to the requested user profile page, in the "incoming invitations section" appears the request I've just sent, but I'm able to click the accept button which returns an error. As I'm not the user of the current user profile page, I shouldn't be able to click that button.
Please fix this, you can determine if the user page is the same as the current user and according to that make clickable that "button".

Screen Shot 2020-08-15 at 1 42 21 PM

Screen Shot 2020-08-15 at 1 43 19 PM

Screen Shot 2020-08-15 at 1 44 12 PM

****

### **Please make the changes required and submit for re-review once you are ready!** 

****
### Status: Changes required. ♻️  
****

Happy coding!  💻  
Have a great day 🙂

If you need more clarifications kindly reach me on slack.
**[TSE:  David Elí]** 
Slack: @ David Eli Martinez Garcia

**Comment by acushlakoncept** [comment]
Thank you @davitomix for the observation.
The `invite_or_pending_btn` has been updated on the user's show page which has already taken care of identifying which user should be able to click accept button. Also, the name of the current user on the nav added to easily identify the current user.

**Review by sumancrest0001 — APPROVED** [review]
**Status: Approved :+1: :1st_place_medal: 
Congratulations TEAM,** All the expected features are added to the project and they are working correctly.
Now, you can move to the next milestone. Having said that, you have only added a few tests with positive scenarios only. I strongly encourage to consider negative test cases also and add a few more tests.
**[Optional] You can consider the empty state and show some random posts when a user is signed up.**
**Happy coding !!!**

**Comment by acushlakoncept** [comment]
> **Status: Approved 👍 🥇 Congratulations TEAM,** All the expected features are added to the project and they are working correctly.
> Now, you can move to the next milestone. Having said that, you have only added a few tests with positive scenarios only. I strongly encourage to consider negative test cases also and add a few more tests.
> **[Optional] You can consider the empty state and show some random posts when a user is signed up.**
> **Happy coding !!!**

Thank you @sumancrest0001, We will surely add more negative test case scenarios also.

**Pull request merged**
