### PR TITLE
Friendship and Friendship requests ERD Diagram

### PR DESCRIPTION
**Pull request by acushlakoncept**
This pull request contains the entity-relationship diagram of friendship and friendship requests. Also, status of the friendship to tell if it is a request or confirmed friendship.

### CODE REVIEW

**Review by majovanilla — CHANGES_REQUESTED** [review]
# Changes required :mag: 


Hey team, 👋

## Good job on this project! 👍

- Good Pull Request Message

### There are still some changes 👇 you need to implement to approve this request 🔍

### Required Changes: ✍️

- The ERD should include the tables for:
    - Likes
    - Comments
    - Posts

- The table friends should be named Friendships since that is what it's storing.
- Remember to specify which ones are the Foreign Keys in each table.
- There is no need to name `user_id` in the user's table, just `id` is enough.
- The status of the Friendship table it's not an `integer`, but a `boolean`. 
- You should specify the type of value for the first 4 elements on the user's table.

### Optional Changes:

If you want to make your project even better 🔥💥, I have a few suggestions you can implement.  These are completely [Optional]: 🦔

- Remember to use `references` when creating your migrations so that rails know which are the Foreign keys of your tables.
`rails generate migration AddUserRefToProducts user:references` generates:
```class AddUserRefToProducts < ActiveRecord::Migration[6.0]
  def change
    add_reference :products, :user, foreign_key: true
  end
end
```

## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes

**Comment by acushlakoncept** [comment]
Thank you for your insightful review. The beam of light you dropped on the review makes it clearer, we will work on the recommended changes.

Thank you.

**Review by uche-inyama — CHANGES_REQUESTED** [review]
## Changes Required

## Hi team :wave: 

Your ERD looks good. 

However, there are no linter validations. Please look into it and resolve the issue.

When you are done submit another code review form.

#### ``` Have  a great day ``` :slightly_smiling_face: 

``` Uchechukwu Henry Inyama ```

**Comment by somoye123** [comment]
> ## Changes Required
> ## Hi team 👋
> Your ERD looks good.
> 
> However, there are no linter validations. Please look into it and resolve the issue.
> 
> When you are done submit another code review form.
> 
> #### `Have a great day` 🙂
> `Uchechukwu Henry Inyama`

Thanks for your review sir
After trying to figure out what the issue is and everything seems to be in place, we discovered that Github (https://github.com/marketplace/actions/lint-action) Actions does not apply to forked repositories.
As such if there is an alternative to this, can you kindly provide a link to help us out.
Thank you

**Review by jofer86 — APPROVED** [review]
## :wave: :wave: Hello! I'm Jorge, and  I'm here to review this Pull Request, let's take a look shall we :eye: :eye: :eye: 
- Changes marked as **[OPTIONAL]** are not hard requirements but are nice to have.
- Hello, I've read the comment about the github linter, if you cannot make it work with a forked repo, you could use https://stickler-ci.com/ although I dunno if the same rules apply. Ideally you should've cloned and worked on a cloned repo instead of a fork, if that doesn't work I suggest you reach out to Bola Buari, head TSE and ask him about an alternative or a more through solution.
- Milestone will be approved but please reach out or see if you can fix the problem on your own.
## `const PROJECT_STATUS = 'Approved'` 🚀 🚀 🚀
--------------------------------------------------------------------
Cheers, 
Jorge Fernando Rincón Figueroa.
Technical Support Engineer.
**Slack: @jofer86**

**Pull request merged**
